# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        local:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public'
        s3:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'aws_client_service'
                bucket: '%env(AWS_BUCKET)%'
        s3async:
            adapter: 'asyncaws'
            options:
                client: 'aws_sync_client_service'
                bucket: '%env(AWS_BUCKET)%'
